events {}

http {
  upstream flask_app {
    server web:5001;  # nginx resolves all scaled instances automatically
  }

  server {
    listen 80;

    location / {
      proxy_pass http://flask_app;
    }
  }
}